### ISSUE TITLE
This isn't an issue, i just didn't know how to contact you lol.

### ISSUE THREAD

**Issue by willy-sk** [DrDesten/DrDestens_McShader#1]
Hi, so this isn't a report of an issue or anything like that, i just didn't know how to contact you.

I would like to use your chromatic aberration for one of my projects.
Also, i love your shaders, it's incredible how your shader improved so much with the time.

Anyways, bye :)

**Comment by DrDesten** [comment]
No problem, you can use my Chromatic Aberration Effect. You don't have to credit me for this, but it would be nice.
Anyways, have a nice day.
