### ISSUE TITLE
Certain dark red blocks, items and entities render black when using TAA

### ISSUE THREAD

**Issue by Pho3nixFeath3r** [DrDesten/DrDestens_McShader#14]
Some red blocks, items and entities render these black ink-like splotches on them, and this makes the nether unplayable with TAA enabled... Hope u can do sum about that pal! Have a great day!

I'm rocking a r5 5600x and an rx 6600 with 32gb of ram, 8 allocated to mc, drivers are up to date. I'll attach screenshots of the glitch/bug and of the resource packs/mods i'm using, as i did with the other issue (just to be sure yk). These are all the affected items i could find, there could be a couple more that i didn't catch.

Other than this issue ur TAA is amazing bro, so much better than the one many mid-range shaders comparable to yours have!! Keep up the good work fam!

![2023-03-25_16 27 58](https://user-images.githubusercontent.com/102165914/227727302-39452099-70ba-4052-873d-58c5412ad087.png)
this is the glitch (more or less evident on certain items)
![Screenshot 2023-03-25 162713](https://user-images.githubusercontent.com/102165914/227727349-ee0f5d64-3e69-4085-9fc1-db2692ff21a1.png)
these items are glitched whenever placed and walked by, some of them (ex: redstone dust) glitch even while holding em
![Screenshot 2023-03-25 162726](https://user-images.githubusercontent.com/102165914/227727412-ff92efda-6353-4e71-aa61-08057d5c04c4.png)
these items and their particles get gliched whenever zoomed in with mods (ex: Zoomify) (note: the witch spawn egg ITEM glitches when dropped on the ground, while the spider egg itself doesent glitch: it's the SPAWNED SPIDER'S eyes that render incorrectly when zoomed upon)
![Screenshot 2023-03-25 162636](https://user-images.githubusercontent.com/102165914/227727460-bc2d5257-a839-4e6f-8919-7f287a5efa19.png)
the glitch happened with these items and entities a couple of times but it's been sporadic and hard to replicate so far
![Screenshot 2023-03-25 152247](https://user-images.githubusercontent.com/102165914/227727526-9923b0a1-8607-43ce-9771-b5a2f393352a.png)
resource packs
![Screenshot 2023-03-25 152420](https://user-images.githubusercontent.com/102165914/227727536-14f5adcf-a56f-419f-bd57-5f86db24485d.png)
mods
[DrDestens+MinecraftShaders+v1.5.7.zip.txt](https://github.com/DrDesten/DrDestens_McShader/files/11069315/DrDestens%2BMinecraftShaders%2Bv1.5.7.zip.txt)
settings

**Comment by DrDesten** [comment]
Can you check if the issue still persists with version 2.0? It released a couple hours ago.

**Comment by Pho3nixFeath3r** [comment]
Same as the other issue, have a great day!!
