### ISSUE TITLE
end sky buggy line

### ISSUE THREAD

**Issue by Artin0123** [DrDesten/DrDestens_McShader#15]
I thought it's abnormal that the end's sky looks like this: 
![2023-04-09_16 55 56](https://user-images.githubusercontent.com/101245159/230764362-ca967822-d7d7-4cd1-adb9-96e7b0d86bd2.png)
minecraft version is 1.19.4 and I use the latest sodium, iris and this shader.

**Comment by DrDesten** [comment]
Can you try with v2.0.2?
It's just released and should contain the fix

**Comment by Artin0123** [comment]
fixed👌
