### ISSUE TITLE
1.5.2 light is overblown?

### ISSUE THREAD

**Issue by OlympicAngel** [DrDesten/DrDestens_McShader#3]
Hey. im here to report that it seems like the overall light is overblown,
i mean, in old version the lighting seems fine,
while in night it looked fairly dark, and there was a need in tourches to see better:
[1.4 image]
https://prnt.sc/22qfcbl
[1.5.2 image]
https://prnt.sc/22qfhok
well EVRYTHING is bright - even dark areas, it looked like as day - with moon and darker sky?

Some more comparsion: (note - it the same time in both pictures)
1.4 - https://prnt.sc/22qfvhp
1.5.2(HIGH) - https://prnt.sc/22qfxrh
1.5.2(MED) - https://prnt.sc/22qg24a
1.5.2(LOW) - https://prnt.sc/22qg051

For both version(1.4 / 1.5.2) I'm using MC 1.17 Fabric client, using OptiFine_1.17.1_HD_U_G9_1 (with optifabric-1.12.6) with the same optifine settings! (the 1.4 pictures is with the HIGH preset).
CPU: ryzen 2700X.
GPU: RTX 2060.

I really like the shaders as they maintain the "vanilla feel" but with extra fx and lighting improvemnet, and i fell in love with the 1.4 version, but it would be great if it could be fixed as i do want the new features of the 1.5 vesrion.

If you need more data let me know!

**Comment by OlympicAngel** [comment]
after some toggeling stuff it seems its because of PBR turned on, after switcing off it looks fine

**Comment by DrDesten** [comment]
I can't open the screenshots (the site doesn't diplay on my end)
Can you please resend them? _I believe you can directly upload them here_

**Comment by DrDesten** [comment]
PBR indeed does seem broken 1.5.2 
Thanks for the report! I'll look into the issue

**Comment by DrDesten** [comment]
I fixed the issue. I will release a fix shortly

**Comment by DrDesten** [comment]
Fix has been released. If you still exerience these problems, please tell me.

**Comment by OlympicAngel** [comment]
Looks great!
