### ISSUE TITLE
TAA breaks the render of transparent blocks

### ISSUE THREAD

**Issue by OlympicAngel** [DrDesten/DrDestens_McShader#4]
Hey again, 
i was expirementing on removing the [ "black dotted grid effect"](https://user-images.githubusercontent.com/48240399/145797481-3e054bf0-9246-4452-8117-4e37ab753b26.png) of AO shadows, and found out that TAA does just the right work.
but after some time - about 1-3 min, it broke the render, it seems it breaks the render of transparent blocks that has smaller hit box then soild block (beds, pots, chest, water, etc..)
adding a video with & without TAA: https://youtu.be/mdRi-Lz4FXk
This render issue come and goes randomly.. (it doesnt happends in 1.4 tho)

Once again I'm using MC 1.17 Fabric client, using OptiFine_1.17.1_HD_U_G9_1 (with optifabric-1.12.6).
Version: 1.5.3.
CPU: ryzen 2700X.
GPU: RTX 2060.
Adding my current settings of the shaders:
```
#Mon Dec 13 12:35:20 IST 2021
SSAO_QUALITY=3
WATER_TEXTURE_VISIBLE=true
DIRECTIONAL_LIGHTMAP=true
WORLD_CURVE=true
PBR_BLEND=0.65
SUNSET_FOG_AMOUNT=10.0
TORCHLIGHT_EXTRA_BRIGHTNESS=1.75
WATER_NORMALS_AMOUNT=0.9
BLOOM_AMOUNT=0.10
HARDCODED_METALS=false
DOF_STRENGTH=0.5
SSAO_STRENGTH=1.00
DOF_DITHER=true
MOTION_BLUR_STRENGTH=0.00
GODRAY_STRENGTH=0.30
CONTRAST=-10
HEIGHT_AO=true
REFRACTION_AMOUNT=0.1
SSR_DEPTH_TOLERANCE=1.5
CHROMATIC_ABERRATION=10
EXPOSURE=0.55
DOF_DOWNSAMPLING=0.2
FOG=2
PHYSICALLY_BASED=true
WATER_NORMALS_SIZE=1.0
BLOOM=false
GODRAY_STEPS=15
DOF_MODE=3
GODRAY_SIZE=0.44
DOF_CHROMATIC_ABERRATION=4
PBR_FORMAT=2
TAA=true
WORLD_CURVE_RADIUS=2048
DOF_MAXSIZE=0.005
FOG_AMOUNT=0.2
MOTION_BLUR_SAMPLES=1
SATURATION=68
```

**Comment by DrDesten** [comment]
Thanks for the report. I'll look into it.

Can you try one thing?
Extract the zip
Go to `\DrDestens_McShader\shaders\lib\kernels.glsl` and open it

Scroll down to the bottom, until you find this:
```glsl
const vec2 TAAOffsets[9] = vec2[](
    // Top Row
    vec2(1./3, -1./3),
    vec2(1./3, 0),
    vec2(1./3,  1./3),
    // Middle Row
    vec2(0, -1./3),
    vec2(0, 0),
    vec2(0,  1./3),
    // Bottom Row
    vec2(-1./3, -1./3),
    vec2(-1./3, 0),
    vec2(-1./3,  1./3)
);
```

Change all of those `vec2(whatever)` to `vec2(0)`. Here, so you can copy it:
```glsl
const vec2 TAAOffsets[9] = vec2[](
    // Top Row
    vec2(0),
    vec2(0),
    vec2(0),
    // Middle Row
    vec2(0),
    vec2(0),
    vec2(0),
    // Bottom Row
    vec2(0),
    vec2(0),
    vec2(0)
);
```

**Please tell me if that changes anything**

**Comment by OlympicAngel** [comment]
Ok, after changing the code you sent it seems like it works just fine, for now im playing for 30min, and so far all good.
i will let you know if it comes by again.

Thanx man!

**Comment by DrDesten** [comment]
Can you try if the issue happens with world curvature off?
(On the unmodified shader)
I think TAA and World Curvature might not be working together nicely
