### ISSUE TITLE
Add setting for cozier lights

### ISSUE THREAD

**Issue by mont-40** [DrDesten/DrDestens_McShader#5]
I really like this shader, though I have one feature request. Lights emit large amount of light, to the point where torchlight is visible at noon and even makes this sheep "glow":

With bloom:
![Glowing sheep with bloom](https://user-images.githubusercontent.com/4014599/148650034-1ce986d0-3bac-45ee-8ae3-c623b6683a23.png)

Without bloom:
![Glowing sheep without bloom](https://user-images.githubusercontent.com/4014599/148650037-1f521027-58d7-4ace-a6df-cbc6f8332544.png)

In both cases the intensity remains the same. Could you make a setting to make lights "cozier", where light sources such as torches give off more subtle lighting?

**Comment by DrDesten** [comment]
There already is a setting for that:
Go to: `Options > Other Stuff > Dynamic Light Brightness`
Turn it to 0 for vanilla light strength
