### ISSUE TITLE
Water has circles on it.

### ISSUE THREAD

**Issue by sertdfyguhi** [DrDesten/DrDestens_McShader#6]
Hi,
When I use your shaders it shows circles on water. Here's an [image](https://i.imgur.com/3m0MNLC.png) of it.
I'm using M1 Mac on 1.18.1.

**Comment by sertdfyguhi** [comment]
Nevermind this issue is duplicated.

**Comment by DrDesten** [comment]
This bug only appears on M1 and some Intel Integrated graphics. It is most likely due to limited openGL support (especially M1)
Only thing you can do (for now) is to disable bump mapping
