### ISSUE TITLE
Weird Stitched Lines around every block? (DrDestens Shaders)

### ISSUE THREAD

**Issue by DanielB156** [DrDesten/DrDestens_McShader#9]
![image1](https://user-images.githubusercontent.com/106673313/171401721-1749abed-0531-4dd6-bc01-46e4d4bf6395.png)

As you can see around the blocks there are some weird lines that aren't normally there. Could this be a setting that needs to be changed or a bug in general?

Thank you, Daniel

**Comment by DrDesten** [comment]
I think what you mean is the dithering of unfiltered SSAO.
I would recommend turning TAA on.

**Comment by DanielB156** [comment]
Hi there, I have fiddled around with settings and when turning on TAA my map seems to glitch out and I see my map in the sky then back down continuously (like a strobe) so instead, I've turned off SSAO (with TAA off) and it has gone. What will these settings affect in terms of gameplay?

**Comment by DrDesten** [comment]
SSAO is an effect that darkens the corners of objects. It's a visual preference.
The TAA issue you described is very weird, but since I'm unable to reproduce it it most likely won't get fixed.
